# https://taskfile.dev
version: '3'
vars:
  BINFILE: template-cli

includes:
  dev: ./Taskfile_dev.yml

tasks:

  default:
    desc: "List tasks"
    cmds:
      - task -a

  linters:
    desc: "Run linters"
    cmds:
      - golangci-lint run --config .golangci.yaml ./...

  binary:
    desc: "Build binary"
    cmds:
      - go generate ./...
      - CGO_ENABLED=0 go build -o template-cli cmd/*.go
    # silent: true

  # tests:
  #   desc: "Run tests"
  #   dir: tests
  #   cmds:
  #     - venom run testsuite.yml --output-dir="log" --stop-on-failure

  snapshot:
    desc: "Create snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean